### ISSUE TITLE
Incorrect request to "localhost"

### ISSUE THREAD

**Issue by jeffteeters** [aleksandr-rakov/elfinder-pyramid#1]
I followed the instructions to install elfinder_pyramid_example.  It works, except display of files fails.  For example, when I select the sample image file, then click on the "preview" icon, the image is not shown, only the name and some metadata.  In the net panel of Firebug, I see there is a request that fails.  URL requested is:

```
http://localhost:6543/static/uploaded/images/love%20is.jpg
```

This is the wrong URL, because the host should not be "localhost".  It should be the actual host used to connect to the server.   A similar problem occurs when trying to open an uploaded PDF file, but not when I view a text file.  All other requests made made by the elfinder code went to the actual host and worked fine.

In development.ini,
host = 0.0.0.0

I'm running the server in a virtual machine, and viewing it over virtual network from a browser running in the host OS.  So the server is effectively on a different machine than the browser.  These problem would not show up if I was running the server and browser both on localhost.  But that's not an option since I want to use this in a real application.

**Comment by aleksandr-rakov** [comment]
Just change this line in development.ini

``` python
elfinder_url= http://localhost:6543/static/uploaded
```

replace localhost to your virtual machine ip address or domain name
