### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by pythonmobile** [aleksandr-rakov/elfinder-pyramid#2]
Seems like the PHP connector got a lot of updates. Any chance those changes will be migrated to the python code anytime soon?

**Comment by aleksandr-rakov** [comment]
Hello!
I have no plans to implement v.2 elfinder protocol.
This is connector for v1 protocol, but it works fine

**Comment by pythonmobile** [comment]
Hi Alexander,

Any particular reason v.2 is not planned for support? Is it because of
extra work? or does it have a problem?

Thanks.

**Comment by aleksandr-rakov** [comment]
I do not know about the problems, but definitely needs more work
